# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "0 0 * * 0-6"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Run Lab01 Web Crawler
      run: |
        cd labs/lab01
        pwd 
        go build web_crawler.go
        go run web_crawler.go

    - name: Run Lab02 Simple Client-Server Demo
      run: |
        cd labs/lab02
        pwd 
        go build client.go
        go build server.go
        go build key_value_store.go
        go run client.go
        go run server.go
        go run key_value_store.go

    - name: Run Lab03 Simple Replication Demo
      run: |
        cd labs/lab03
        pwd 
        go build primary.go
        go build secondary.go
        go build client_01.go
        go build client_02.go

        go run primary.go
        go run secondary.go
        go run client_01.go
        go run client_02.go
